// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AesCtrCrypt(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function HMAC_SHA256(arg1:string):Promise<string>;

export function MD5(arg1:string):Promise<string>;

export function Sha1(arg1:string):Promise<string>;
