// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AesCtrCrypt(arg1) {
  return window['go']['main']['App']['AesCtrCrypt'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HMAC_SHA256(arg1) {
  return window['go']['main']['App']['HMAC_SHA256'](arg1);
}

export function MD5(arg1) {
  return window['go']['main']['App']['MD5'](arg1);
}

export function Sha1(arg1) {
  return window['go']['main']['App']['Sha1'](arg1);
}
